version: "3"
services:

  redis:
    image: redis:alpine
    networks:
      - gameeapi

  api:
    build: .
    depends_on:
      - redis
    ports:
      - 8087:8080
    networks:
      - gameeapi

networks:
  gameeapi:
